# Generated by Django 4.2.3 on 2024-01-27 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StoreBookModel',
            fields=[
                ('book_id', models.IntegerField(primary_key=True, serialize=False)),
                ('book_name', models.CharField(max_length=255)),
                ('author_name', models.CharField(max_length=255)),
                ('book_price', models.IntegerField()),
                ('category', models.CharField(choices=[('Humor', 'Humor'), ('Sifi', 'Sifi'), ('Romantic', 'Romantic'), ('Drama', 'Drama'), ('Action', 'Action'), ('Thriller', 'Thriller')], max_length=255)),
                ('first_pub', models.DateTimeField(auto_now_add=True)),
                ('last_pub', models.DateTimeField(auto_now=True)),
                ('book_description', models.TextField()),
            ],
        ),
    ]
