# Generated by Django 4.2.3 on 2024-01-27 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UpdateUserInfoModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_image', models.ImageField(blank=True, upload_to='photos/userimg')),
                ('phone_number', models.CharField(max_length=11)),
                ('dob', models.DateField()),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Others', 'Others')], max_length=200)),
                ('age', models.IntegerField()),
                ('address', models.CharField(max_length=255)),
                ('description', models.TextField(max_length=100)),
            ],
        ),
    ]
